# Generated by Django 5.2.5 on 2025-09-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='pending', max_length=30),
        ),
    ]
